spec/fiddle-bisect-parser.spec.ts, spec/issue-parser.spec.ts
In tests, move repeated code into reusable functions to avoid repetition.
There's not much to this PR; it's simple refactoring I did while reading last weeks' commits
=> test: avoid repetition in test scaffolding code

modules/broker/test/broker.spec.ts, modules/shared/tsconfig.base.json
Works around an upstream typing issues with URL, URLSearchParams. Without this, the broker's tests fail when a type for URLSearchParams can't be found.
Looks like this might've broken as a side-effect of specifying ES2019 in tsconfig.base.json in f6254f89 ?
Xref: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34960
=> fix: broker test import URLSearchParams explicitly

broker.config.js, modules/broker/package.json, modules/broker/src/main.ts, modules/broker/src/server.ts, yarn.lock
The broker serves http by default. If the cert & keyfiles are set, broker will also serve https.
In addition, the broker's settings (e.g. what port to use) now reside in `broker.config.js` where the bot and runners can pick up the values too.
=> feat: broker serve both http and https

modules/broker/src/task.ts, modules/broker/test/broker.spec.ts, modules/runner/src/main.ts
For clarity, use the same names that the rest of the Node world is using.
before: 'linux', 'macos', 'windows'
after: 'darwin', 'linux', 'win32'
=> refactor: use process.platform os names

modules/broker/src/main.ts, modules/broker/src/server.ts, modules/broker/src/task.ts, modules/broker/test/broker.spec.ts, modules/runner/src/main.ts
- add better filtering options when querying jobs, e.g. allowing multiple vals in key/value pairs, negation, sub-properties. From the code:
```js
/**
* Conventions:
* - `.` characters in the key delimit an object subtree
* - `,` characters in the value delimit multiple values
* - a value of `undefined` matches undefined values
* - a key ending in `!` negates the filter
*
* Examples:
* - `jobs?foo=bar`          - `o[foo] == bar`
* - `jobs?foo!=bar`         - `o[foo] != bar`
* - `jobs?foo=undefined`    - `o[foo] === undefined`
* - `jobs?foo=bar,baz`      - `o[foo] == bar || o[foo] == baz`
* - `jobs?foo.bar=baz`      - `o[foo][bar] == baz`
* - `jobs?foo!=undefined`   - `o[foo] != undefined`
* - `jobs?foo!=bar,baz`     - `o[foo] != bar && o[foo] != baz`
* - `jobs?foo.bar=baz,qux`  - …
```
=> feat: add more filter options when querying jobs

integration-tests/test/broker-runner.test.ts, modules/broker/.gitignore, modules/broker/src/server.ts, modules/runner/src/runner.ts
In Runner, replace `child_process.execFile()` with `child_process.spawn()` so that we can get a ChildProcess and listen for `'data'` events from stdout/stderr.
One tradeoff is the addition of new state properties in Runner, e.g. jobId and etag are now private properties in the runner class. This has a bit of a smell because these state properties are very short-lived and could live on the stack in the `poll()` function, but doing so got kind of messy because the actual calls to patch() are now nested a few calls deep in the call stack, so keeping all the callers up-to-date with the updated etags was getting messy.
=> feat: add logging support to runner

modules/bot/Procfile, modules/bot/package.json, package.json
Uses https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-multi-procfile to allow multiple Heroku Procfiles.
Serving the app at https://damp-temple-23212.herokuapp.com/. Currently works off of my test app, but the Heroku Config Vars can be changed to use the actual Electron one.
=> chore(bot): configure heroku procfile

integration-tests/test/broker-runner.test.ts, modules/broker/src/task.ts
Fixes an integration test that broke from the `Task.log` refactor in 52aa2dd18ee4dafb92fbc0c45b1648a0b152cdc2.
=> test: fix integration tests

modules/bot/src/github-client.ts, modules/bot/test/github-client.spec.ts
In the probot client code, type the context parameters as 'probot.Context' instead of as 'any'.
This is a small type safety improvement I found while working on the environment variable PR.
=> refactor: use probot.Context type in probot client

modules/bot/src/github-client.ts
This fixes the broken log URL that we saw yesterday. The occurs when BROKER_BASE_URL has a trailing slash because the link was built naively with `${base}/path`. It now uses `new URL(/path, base)` which works whether or not there's a trailing slash.
=> fix: broken log URL in issue comments

modules/broker/package.json, modules/broker/src/log.ts, modules/broker/src/server.ts, modules/broker/test/broker.spec.ts, modules/shared/src/issue-parser.ts, yarn.lock
This PR tries to address [a few warnings](https://lgtm.com/projects/g/electron/bugbot/?mode=list) that LGTM found in our codebase, the primary one being that we didn't sanitize the data that was passing into express' Response.send() calls.
- before calling expresss.Response.send(), filter the data through escapeHtml()
- remove a redundant regex char in the log matching code
- replace an inefficient regex when extracting the job id from `/api/jobs/${id}/log`
- try to avoid some gotchas in matching a gist.github.com URL
Also, while on the subject... any opinions on whether it would be useful to add LGTM to the Actions for sniffing PRs?
=> feat: sanitize broker responses

modules/bot/src/github-client.ts, modules/broker/package.json, modules/runner/package.json, modules/runner/src/runner.ts, yarn.lock
Currently we use `fetch()` in modules/bot/ and modules/broker/tests, and `got()` in modules/runner/ .
This minor refactor PR changes the latter to avoid duplicate libraries.
=> refactor: replace got() with fetch() in runner

modules/broker/src/server.ts, modules/broker/test/broker.spec.ts
In preparation for deploying the broker to Heroku, this PR adds a `$PORT` environment variable fallback for the express server.
Each Heroku web process must bind to a port specified by the `$PORT` environment variable, which is assigned by Heroku itself when a dyno is spun up. See Heroku's [Runtime Principles](https://devcenter.heroku.com/articles/runtime-principles#web-servers) doc for more information.
=> feat(broker): add PORT as env variable fallback

modules/broker/src/server.ts
Instead of using `path.basename` and manual string manipulation, let express handle getting information from the URL for us instead by using route parameters.
=> fix: use express routing params

README.md, modules/runner/package.json, modules/runner/src/runner.ts, yarn.lock
This is needed when `electron-fiddle` is only part of the invocation, e.g. when invoking headless on Linux with `xvfb-run electron-fiddle`.
=> feat: allow multiple args in BUGBOT_FIDDLE_EXEC env var

integration-tests/test/broker-runner.test.ts, modules/runner/src/runner.ts
Right now the runner contacts the broker every single time there's a line of log data to append from electron-fiddle.
This PR adds a debounce timer to batch them up and reduce the number of round trips needed.
The current interval is 2 seconds. This is configurable via the Runner constructor opts object so that tests don't have to wait that long. I don't see a use case for end users so I didn't add an environment variable, but I don't mind adding it if someone else sees a use for it.
=> feat: batch up electron-fiddle to send to broker

integration-tests/tsconfig.json, package.json
Pretty straightforward. It calls 'tsc' on all the submodules.
Also fixes the references in integration-tests, since running `yarn tsc` uncovered a broken path there.
=> build: add 'tsc' to package.json's scripts

modules/bot/src/github-client.ts
I realized while writing tests that we used `GitHubClient:` and `github-client:` prefixes in the bot module. This PR makes them all `GitHubClient:`.
=> fix: uniformize bot debug prefix

modules/broker/package.json, package.json
Heroku's workspace support isn't great, and it looks like our latest build failed because their Node.js buildpack loaded the LTS version of Node.js.
```
error @electron/bugbot-broker@0.0.1: The engine "node" is incompatible with this module. Expected version ">=16.0.0". Got "14.17.2"
error Commands cannot run with an incompatible environment.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
```
This PR moves the `engines` check to the global `package.json` so that Heroku can detect that we need Node 16.
=> fix: define `engines` in global `package.json`

modules/bot/src/github-client.ts, modules/bot/test/github-client.spec.ts
Ref #81
This PR uses `nock` to intercepts HTTPS requests to the GitHub API and checks if the Probot client hits the correct endpoints for commenting and labelling.
See https://probot.github.io/docs/testing/ for more info.
A few notes:
* The tests added are not very granular. Each one covers an entire use-case for `commentBisectResult()` and has asserts for each API request. Since I needed to mock all the requests to run through `commentBisectResult()` anyways, I decided to assert for all of them along the way.
* We could extend this Nock testing to the rest of the `github-client.spec.ts` tests in a future PR.
* There's a bit of coverage left that's annoying to pick up given that we're not fully in on Nock yet (the contents inside the polling interval outside of the `commentBisectResult` …
=> test(bot): use nock to test post-bisect Probot interactions

integration-tests/test/broker-runner.test.ts, modules/bot/src/api-client.ts, modules/bot/src/github-client.ts, modules/broker/package.json, modules/broker/src/server.ts, modules/broker/src/task.ts, modules/runner/package.json, modules/runner/src/runner.ts, modules/shared/src/interfaces.ts, yarn.lock
no functional changes.
This is the result of me re-enabling the eslintrc warnings long enough to fix the ones that were quick & easy fixes. The rules are still disabled because the remaining warnings are either larger in scope or will be refactored away soon anyway as a side-effect of adding the matrix.
=> refactor: fix some warnings

integration-tests/jest.config.js, jest.config.js, modules/bot/jest.config.js, modules/broker/jest.config.js, modules/runner/jest.config.js, modules/shared/jest.config.js
Does what it says on the tin. Based on [this stackoverflow](https://stackoverflow.com/questions/60347361/jest-projects-in-a-monorepo-unable-to-find-config-files-in-projects) pointer about pointing the modules' `rootDir` at the top-level project. Remove  config settings that have no effect.
*edit:* This lowers coverage slightly because `modules/runner/runner.ts` is now included in the reports.
=> test: include integration tests in test coverage

.eslintrc.js
After #80, navigating to a config JS file in the root folder gives the following ESLint error:
```
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: .eslintrc.js.
The file must be included in at least one of the projects provided.
```
This PR adds the ESLint and Jest configs to the ESLint ignore patterns.
=> chore: ignore config files in eslintrc

modules/broker/README.md
Move the Broker interfaces document from hackmd into the submodule's README.md.
=> docs: move 'interface' doc from hackmd to the repo

README.md, modules/bot/package.json, modules/bot/src/github-client.ts, modules/bot/test/github-client.spec.ts, yarn.lock
Closes #97.
The base logic here is in the `setIssueComment` function, which takes in a Probot context and a string for the comment body.
It was a pain to test these changes with the test infrastructure set up in #91, so I had to refactor a bunch of things.
In the client's source code:
* The polling logic is now in a recursive `setTimeout` that resolves a Promise when the job is done. This improves our previous `setInterval` implementation, which actually failed when if the timer's interval was too low (see [ESLint rule](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-misused-promises.md)).
* The code is broken up into more modular pieces (a new intermediary `runBisectJob` is added) and function names are changed to be more accurate …
=> feat(bot): self-update bot comments

modules/bot/src/electron-versions.ts
If we somehow got an incomplete list of Electron releases from the CDN, it's just possible that bugbot could freeze up in an infinite loop because of a bug in some new code that I wrote.
The preconditions to tickle this bug are very unlikely, but this PR fixes it anyway.
=> fix: unlikely but possible infinite versions loop

README.md, modules/broker/src/auth.ts, modules/broker/src/server.ts, modules/broker/test/auth.spec.ts, modules/broker/test/broker.spec.ts
Allows the broker to use a `BUGBOT_AUTH_TOKEN` environment variable if one is present, granting that token value access to all scopes.
Fixes #111.
=> feat: use explicit token passed to broker in env

modules/bot/src/broker-client.ts, modules/broker/src/server.ts
The Heroku bot isn't successfully posting jobs to the broker, and it's not clear why.
This PR adds some tracer debug() calls to help triage this issue / future issues.
=> chore: add debug calls when new jobs are posted

modules/bot/src/github-client.ts, modules/bot/test/github-client.spec.ts
Closes #106.
Takes @ckerr's suggestion of borrowing the code snippet from `trop`. As a side effect, this means I won't have access to the `/test` command in production. 😅 
This PR also brings a couple more `nock` goodies.
* The unused interceptor validator now prints out which interceptors are remaining.
* Nock scope is instantiated in the `beforeEach()` of each test.
=> feat(bot): only allow commands for maintainers

modules/bot/src/electron-versions.ts, modules/bot/test/electron-versions.spec.ts
Increase the number of supported branches to four as per https://github.com/electron/electronjs.org/pull/5463
=> chore: increment number of supported branches to 4

modules/bot/src/github-client.ts
In preparation for #102, this makes the broker polling logic reusable to accommodate for more use-cases.
I didn't test this in production, but the existing unit tests passed without fail.
=> refactor(bot): move polling logic into helper func

integration-tests/test/broker-runner.test.ts, modules/bot/src/github-client.ts, modules/runner/src/main.ts, modules/runner/src/runner.ts, modules/shared/src/rotary-loop.ts
**Note: stacks on top of https://github.com/electron/bugbot/pull/126, which should land first.**
The previous runner polling loop fired every N msec whether the previous poll was done or not. This caused the same runner to claim a job twice in integration tests. Also, Electron Fiddle doesn't like to have two copies of itself running at once, so the runner having two parallel jobs is problematic even when they're not both the same job.
The new loop waits for the previous call to finish first, _then_ sleeps N msec.
*edit:* don't worry about the temporary drop in coverage. The integration test PR at the end of this PR chain will fix it. Honest!
=> fix: runner polling loop can accidentally run jobs in parallel

integration-tests/test/bot-broker-runner.test.ts, integration-tests/test/broker-runner.test.ts, modules/bot/src/broker-client.ts, modules/bot/src/github-client.ts, modules/bot/src/issue-parser.ts, modules/bot/test/github-client.spec.ts, modules/broker/src/server.ts, modules/broker/src/task.ts, modules/broker/test/broker.spec.ts, modules/runner/src/runner.ts
Fixes #137.
This change pulls in the `shared/` workspace into our coverage reports :tada: but I didn't find any good docs on best practices for monorepo imports like this, so I'm not sure if there aren't other side-effects. Were there other reasons that `build/` was used?
=> build: import other workspaces from src/ instead of build/

modules/bot/src/table-generator.ts
In the "Electron" column, have the version number link to that version's release + release notes.
before:
| Electron                                                            |                                                                             Linux |
| :------------------------------------------------------------------ | --------------------------------------------------------------------------------: |
| 12.0.0 | [Failed&ensp;🔴](http://localhost:43493/log/9b40d7ec-878c-4416-b181-968ed38642c2) | +1ms
after:
| Electron                                                            |                                                                             Linux |
| :------------------------------------------------------------------ | …
=> feat: in test matrix comment, link to Electron release

integration-tests/package.json
when `yarn build` is run, have integration-tests/ call `tsc -b` instead of `# no-op` because the latter does not work on PowerShell: 
```
> @electron/bugbot-runner-integration-tests
$ # no-op
'#' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
```
=> build: omit noop from integration-tests package.json

.eslintrc.js, modules/bot/src/github-client.ts
As discussed last Friday in the Slack channel, we wanted to get this working first and then make it a little nicer. Friday's PR got it working, so this PR makes it a little nicer.
1. When running the test matrix, ratelimit how frequently the probot client patches its issue comment. The previous implementation patched it every time a job finished. This works, but could generate a lot of traffic since we're potentially running tens of jobs per issue.
2. After all the test promises for an issue settle, send a final patch that bypasses the ratelimit. This is to ensure the final comment has all the results.
3. When patching the bot's comment, do nothing if new comment === old comment.
=> feat: limit how frequently the bot updates its issue comment

integration-tests/test/bot-broker-runner.test.ts, integration-tests/test/broker-runner.test.ts, modules/bot/src/broker-client.ts, modules/bot/src/github-client.ts, modules/bot/src/issue-parser.ts, modules/bot/test/github-client.spec.ts, modules/broker/src/server.ts, modules/broker/src/task.ts, modules/broker/test/broker.spec.ts, modules/runner/src/runner.ts
This reverts commit 51afb54429a955fd50b25057255f909c023b7366.
=> Revert "build: import sibling workspaces from src/, not build/ (#138)"

modules/bot/src/github-client.ts, modules/bot/src/table-generator.ts
Previously we had a placeholder comment saying 'queueing bisect job'; this PR changes that to show a matrix showing all the jobs that are pending.
=> feat: better 'hello world' comment for test matrix

modules/bot/src/broker-client.ts
No production changes; just fixes a wart in our logs. Right now we have a few places that say something like this:
```ts
d('url', url);
```
Which generates a prolix multiline dump of the URL object:
```
2021-07-21T19:46:43.774408+00:00 app[web.1]: 2021-07-21T19:46:43.774Z bot:BrokerAPI:getJob url URL {
2021-07-21T19:46:43.774409+00:00 app[web.1]: href: 'https://bugbot-broker.herokuapp.com/api/jobs/8f6dce53-3380-4a80-b47a-27b11c1d5aa2',
2021-07-21T19:46:43.774410+00:00 app[web.1]: origin: 'https://bugbot-broker.herokuapp.com',
2021-07-21T19:46:43.774410+00:00 app[web.1]: protocol: 'https:',
2021-07-21T19:46:43.774411+00:00 app[web.1]: username: '',
2021-07-21T19:46:43.774411+00:00 app[web.1]: password: '',
2021-07-21T19:46:43.774412+00:00 app[web.1]: host: 'bugbot-broker.herokuapp.com', …
```
=> chore: terser URL strings in debug logs

modules/runner/src/runner.ts
Similar to the narrowly-focused bot logging PR from Wednesday (#150).
- When logging a json patch, show one patch per line
- Log the job being patched, rather than the Task object that holds the job. The Task has a lot of data unrelated to the json patch, e.g. the log buffer.
- When spawning, log the exec + args in a method that is easier to copy & paste elsewhere in case you need to reproduce the test manually. Currently ["it", "is", "formatted", "like", "this"] which is not convenient for copy -> paste -> run from a command line.
=> chore: slightly terser runner debug logging

modules/runner/src/runner.ts
Only put the runner to sleep for intervalMsec when there are no jobs for it to run.
Previously it was going to sleep after every job it finished.
=> feat: do not sleep when jobs are waiting in runner

modules/bot/src/github-client.ts
Does what it says on the tin -- in bugbot's test matrix issue comment, add a link to the gist being tested.
=> feat: add a gist link to the test matrix comment

integration-tests/test/bot-broker-runner.test.ts, modules/bot/src/github-client.ts, modules/bot/test/github-client.spec.ts
Fixes #153.
When running a task, e.g. a bisect or a test matrix, keep patching the current comment until the task is done. Once it's done, make a new comment so that future invocations won't overwrite the previous work.
I wonder if this will cause other (smaller) issues; but of the ideas listed in that ticket so far, this approach makes the most sense to me.
=> feat: bot should make new comments for new tasks

README.md, modules/bot/package.json, modules/broker/package.json, modules/broker/src/server.ts, modules/runner/package.json, modules/shared/package.json, modules/shared/src/log-metric.ts, yarn.lock
Adds some code to log metrics to a remote server, specifically one hosting an instance of [Grafana Loki](https://grafana.com/oss/loki/). Metrics are done as send-and-forget with only some logging on top of the request to the remote server.
To enable the feature the `BUGBOT_LOG_METRICS_URL` env var must be set, then metrics will be sent there. Additionally, if the request requires authentication, the `BUGBOT_LOG_METRICS_AUTH` env var can be set to pass the correct HTTP `Authorization` header (using the `Basic` auth scheme). (Maintainers: see slack for more context here.)
=> feat: add remote metric logging

modules/bot/src/broker-client.ts, modules/bot/src/github-client.ts, modules/bot/test/github-client.spec.ts
We're not using the `bot_client_data` field, so this PR removes the code that touches it.
*edit:* literally no new code. Coveralls dropped because some of the removed LOC had test coverage.
=> refactor: remove unused bot BrokerClient.completeJob()

modules/broker/src/task.ts
Does what it says on the tin.
The broker is stripping out empty lines from the log, even if those empty lines make the output more human-readable.
=> fix: don't strip empty lines from the runner's log

.eslintrc.js
A fresh checkout of bugbot no longer passes lint tests due to new `@typescript-eslint/restrict-template-expressions` warnings. As a workaround, this PR disables those warnings.
As an example,
```ts
jobId: JobId = .. ;
console.log(`${jobId});
```
will generate a warning even though [JobId is a type alias for string](https://github.com/electron/bugbot/blob/3c15faaba1eeedbd276104b7770d19769f43cdea/modules/shared/src/interfaces.ts#L13). eslint thinks that it is an 'any', either because it's failing to resolve the correct type, or because it is intentionally restricting type aliases because it's bad practice to assume an alias' type.
Other alternatives would be
- remove the type aliases and just have jobIds be strings
- get more creative about how they're used, e.g. replace `api/jobs/${jobId}` …
=> build: disable new eslint warnings

modules/runner/src/runner.ts, modules/runner/src/task.ts
No behavioral changes; just moving the Task code into its own file to make the existing `runner.ts` and new `task.ts` files each a little more single-topic.
=> refactor: move Runner's Task class to its own file

modules/bot/src/github-client.ts
As mentioned earlier today, this is still flushing out the queue of a couple of refactors that I did during the end of the last sprint.
When building a test matrix, have the probot bot try to periodically update the issue comment every few seconds.
GithubClient.setIssueComment() still has a safety check to do nothing if the content is unchanged since last time, so we still won't be generating redundant network traffic. The idea here is to try and flush new changes to the matrix back up to github more quickly.
=> refactor: change how issue comment is updated during test matrix

.eslintrc.js, integration-tests/package.json, integration-tests/test/bot-broker-runner.test.ts, integration-tests/tsconfig.eslint.json, integration-tests/tsconfig.json, modules/shared/tsconfig.base.json
Re-fix linting in `integration-tests/`.
Config changes:
1. Fix side-effects introduced by #141. That PR did fix the PowerShell issue, but introduced a side-effect that "yarn build" created unwanted .js files for integration tests. This PR goes back to making integration-tests' "yarn build" a no-op, but this time uses a more cross-platform no-op: `"build": "run-p -s"` (do nothing, and do it silently).
2. The integration tests directory was hitting the same include/exclude issue we've had in other submodules. Fixed by using the same dual tsconfig approach as the other submodules (see #99). (This is slightly odd here since there are no non-test files, but has the advantage of consistency with the rest of the repo)
3. Add `downlevelIteration: true` to the shared base tsconfig file so that …
=> fix: linting in integration-tests submodule

modules/runner/package.json, yarn.lock
Runs the runner module using [pm2]().
I did look up what the [difference between the `pm2` and `pm2-runtime`](https://stackoverflow.com/a/58168109) commands is and I ultimately decided on `pm2-runtime` because I find that easier to check up on personally, but I'm happy to change the command to `pm2` if we want to run it as a daemon and have the runner controlled in the background.
Fixes #162.
=> feat: make the runner more resilient to crashes

modules/bot/src/github-client.ts, modules/broker/src/server.ts
Hopefully this moves our only metric logging right now to a better spot that better represents the actual invocations of the bot. It also actually records the issue ID now.
Fixes #161
=> fix: move metric logging to a better spot

modules/bot/src/github-client.ts
The `issue.id` field was unique across all issues everywhere, which isn't exactly what we wanted. Instead, use the user-friendly issue URL.
=> fix: use the issue URL instead of unique issue ID

.github/workflows/semantic.yml, .github/workflows/test.yaml
Updates and pins SHAs for actions. Should clear deprecation warnings on workflow runs.
=> ci: update GitHub actions workflow

yarn.lock
This clears most but leaves one Dependabot alert which is still needs to be resolved upstream.
=> chore: update deps to clear some audit warnings
