src/client/github-client.ts, src/client/runner-api.ts
This PR connects runner and client together.
=> feat: connect runner and client

src/client/github-client.ts, src/client/runner-api.ts
Adds some formatting to the response message from the bot after completing a bisect.
---
🤖 The bisect ✅ succeeded!
* **Good version**: 1.2.3
* **Bad version**: 4.5.6
🤖 The bisect ❌ failed. This Fiddle did not narrow down to two versions in the specified range.
=> feat: bot responds with a formatted message

modules/runner/package.json, modules/runner/src/main.ts, modules/shared/src/env-vars.ts, modules/shared/tsconfig.base.json, yarn.lock
Updates the runner module to poll jobs to execute from the new broker module.
**NOTE**: Only executes bisect jobs currently.
=> feat: update runner to poll from broker

modules/broker/src/task.ts, modules/broker/test/broker.spec.ts
Rename 'bisect_result' to 'result_bisect' and add a test to confirm it. :slightly_smiling_face:
=> fix: a broker job property differing from the spec 

modules/broker/src/task.ts, modules/broker/test/broker.spec.ts, modules/runner/src/main.ts
This should allow better error reporting for failed jobs and also allow other runners to pick up tasks that a runner failed due to system error.
=> feat: add job properties: current, history, last

modules/broker/src/server.ts, modules/broker/src/task.ts, modules/runner/src/runner.ts, modules/runner/tsconfig.json, modules/shared/src/interfaces.ts, package.json
Some simple integration tests for broker & runner. Confirms what tasks a runner will & won't claim and that it updates the job correctly if a bisection run succeeds.
=> test: add some broker/runner integration tests

integration-tests/package.json, modules/broker/src/task.ts, modules/broker/test/broker.spec.ts, modules/runner/src/runner.ts, modules/shared/src/interfaces.ts
No functional changes, but better type checking via better type & interface declaration
=> refactor: better sharing of types and interfaces

modules/bot/src/github-client.ts
when adding a 'job complete' comment, add/remove labels as appropriate
=> feat: bot add/remove labels on bisect complete

modules/bot/src/github-client.ts, modules/broker/src/log.ts, modules/broker/src/server.ts, modules/broker/src/task.ts, modules/broker/test/broker.spec.ts, modules/shared/src/interfaces.ts
Fixes https://github.com/electron/bugbot/issues/36.
- in the issue comments, add a link to the fiddle log page
- in the fiddle log page, make links and electron releases clickable
=> feat: logging link

app.json
=> chore(bot): add app.json schema

integration-tests/package.json, modules/bot/package.json, modules/shared/package.json, yarn.lock
No code changes.
- Remove a couple of dependencies that we declared but didn't use (e.g. `smee-client` in bot, `dayjs` in integration-tests)
- Add a couple of dependencies that we used but didn't declare (e.g. debug, semver, and uuid in the shared module)
*edit:* added an empty commit to please the semver bot
=> update the 'package.json' files from depcheck runs

modules/runner/src/runner.ts
A small refactor to make public Task API that corresponds to the deliverables that Runner cares (e.g. 'Claim this task', 'Set the results') and make the rest private (e.g. the JSON-Patch patching is now a private method).
1. Make `Task.sendPatch()` private
1. Extract-method the "claim this task" code from `Runner.poll()` to new public function `Task.claimForRunner()` 
1. Move `Runner.patchResult()` code to new public function `Task.sendResult()`
1. Decouple `Runner.runTest()` and `Runner.runBisect()` from patching -- they both now return a Partial&lt;Result&gt; which `Runner.poll()`passes to `Task.sendResult()`
=> refactor: put task-patching code to the Task class

modules/bot/package.json, modules/bot/src/broker-client.ts, modules/bot/src/github-client.ts, modules/bot/src/table-generator.ts, yarn.lock
Watch this on 2x speed to figure out where I am so far:
https://www.loom.com/share/eab410bc7eb54172b9fe1ea0237b34f0
I verified that this works manually (see video), but there are no tests written for the bot flow or the table generator.
=> feat(bot): add `/bugbot test` command handler

modules/bot/src/github-client.ts
Bugbot tries to update its existing issue comments; but if that fails, it should post a new comment instead.
This fixes an issue that arises if bugbot's previous comment is deleted :roll_eyes:  and the probot client has the deleted comment id in its cache.
=> fix: bot should post a new comment if patching the old one fails

modules/bot/src/github-client.ts
=> fix: handle >1 concurrent job per issue in the bot

.eslintrc.js, modules/bot/src/broker-client.ts, modules/bot/src/github-client.ts, modules/bot/src/issue-parser.ts, modules/bot/src/mdast-util-heading-range.d.ts, modules/bot/src/table-generator.ts, modules/broker/src/server.ts, modules/runner/src/runner.ts, modules/runner/src/task.ts, modules/shared/src/log-metric.ts
This PR turns back on some lints that were turned off by fixing the places where they were causing issues. Most changes are trivial, but there's one or two that required adding a little new code where lints were showing a potential bug.
=> lint: fix and turn on lints that are turned off

modules/bot/src/issue-parser.ts, modules/bot/test/fixtures/issue-random-capitalization.md, modules/bot/test/issue-parser.spec.ts
=> fix(bot): case insensitive markdown heading parsing

integration-tests/package.json, integration-tests/test/bot-broker-runner.test.ts, modules/issue-manager/package.json, modules/issue-manager/src/github-client.ts, modules/issue-manager/src/issue-parser.ts, modules/issue-manager/test/github-client.spec.ts, modules/issue-manager/test/issue-parser.spec.ts, modules/runner/package.json, modules/runner/src/main.ts, modules/runner/src/runner.ts, yarn.lock
Meet the new boss, same as the old boss.
=> build(deps): switch to @electron/fiddle-core package

.github/workflows/semantic.yml
=> chore: add semantic commit check

README.md, modules/issue-manager/src/github-client.ts
=> chore: update stale links

.github/workflows/semantic.yml, .github/workflows/test.yaml
=> ci: bump deps to clear deprecation warnings
